apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ekscluster
  region: ap-south-1
nodeGroups:
   - name: ng1
     instanceType: t2.micro
     desiredCapacity: 2
     ssh:
        publicKeyName: keycloudclass
   - name: ng2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: keycloudclass